### PR TITLE
Initial push

### PR DESCRIPTION
**Pull request by jfsinmsp**

### CODE REVIEW

**Comment by jfsinmsp** [comment]
Are permissions changed so that Chris and I can push into main now too?

**Comment by dmajones** [comment]
@jfsinmsp The initial deployment is now complete. The repo is live here https://docs.netapp.com/us-en/ontap-apps-dbs/ 
I noticed that harmony_enabled was removed in the project.yml file... does this repo require localization?

**Comment by jfsinmsp** [comment]
Not a clue. I'll defer to Megan/Ed on what that should be. It appeared to be commented out in the original.

**Comment by dmajones** [comment]
Thanks @jfsinmsp Typically the answer is yes...IE's process is to localize all repos, but I didn't know if this repo was an exception or not. @netapp-ehoffman @ntap-bmegan Please advise whether harmony should be enabled for this particular repo.

**Comment by jfsinmsp** [comment]
If someone can tell me what to add, or point me at a NetAppDocs help doc, I'll take care of it. I just tested a push for a minor fix, and it worked as expected.

**Comment by dmajones** [comment]
Thanks @jfsinmsp ...I'll take care of enabling harmony as part of the initial deployment, but I'd like to hold until @netapp-ehoffman or @ntap-bmegan confirms this repo is not an exception to our standard process.

**Comment by ntap-bmegan** [comment]
The only EN-only repos are the autogenerated ones, so Harmony should be enabled. 

@jfsinmsp - Because of the merge conflict, you should pull public main back to internal main and push to internal main. Just matching the content of the files will not prevent ongoing merge conflicts. 

In the local -internal clone:

```
git switch main
git pull origin main
git checkout -b enable-harmomy
git switch enable-harmomy
git pull public main
```

Then enable harmony for prod in `project.yml` by adding the line shown below:

```
  prod:
    pdf_enabled: true
    harmony_enabled: true
```

Then push:

```
git push origin enable-harmomy
````

There will be no visible difference in the preview site but builds should run normally. 

Then publish this branch the way you did the last one. After completing the internal main PR:

```
git push public enable-harmomy
```

Then open the PR in public to merge the branch to main. There won't be any preview site. Just wait for checks to run, then complete the merge. You will not need admin assistance, and you should not get any merge conflicts. Tag me if you do get a conflict.

**Comment by jfsinmsp** [comment]
Done.

**Pull request merged**
